name: Deploy Migrations to Production
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PROJECTID }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: |
          echo "SUPABASE_PROJECT_ID=$SUPABASE_PROJECT_ID" | base64 > secrets.txt
          echo "PRODUCTION_DB_PASSWORD=$PRODUCTION_DB_PASSWORD" | base64 >> secrets.txt
          cat secrets.txt
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
